version: '3'
services:
  web:
    build: .
    image: blog
    container_name: blog
    command: jekyll serve --source /srv/jekyll --destination /srv/jekyll/_site --host 0.0.0.0 --port 8080 --livereload --livereload-port 4000
    volumes:
      - .:/srv/jekyll
    ports:
      - "8080:8080"
      - "4000:4000"
